version: '3.9'

services:

  postgres:
    image: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: lrlc
      POSTGRES_USER: yakovchuk.ea

#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - 8080:8080